image:
  name: registry.gitlab.exphost.pl/exphost-controller/webui
  pullPolicy: Always
  tag:
ingress:
  annotations:
    cert-manager.io/cluster-issuer: acme-issuer
global:
  domain: example.com
endpoints:
  authendpoint:
    url: "https://auth.example.com/dex"
    # secret:
